version: 2
jobs:
  deploy-not-release:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Login to project
          command: |
            cat < .npmrc
            //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
            EOF

      - run:
          name: Publish to NPM
          command: npm publish 

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  deploy_staging:
    jobs:
      - deploy-not-release:
          context: techgreens-context
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/