version: 2
jobs:
  deploy-not-release:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Login to project
          command: |
            cat >> .npmrc << EOL
            //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
            EOL

      - run:
          name: Publish to NPM
          command: |
            PACKAGE_VERSION=$(cat package.json \
              | grep version \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",]//g' \
              | tr -d '[[:space:]]')

            TAG=$(echo $PACKAGE_VERSION | sed -n 's/^[0-9]*\.[0-9]*\.[0-9]*\(\-\([a-z]*\)\.*[0-9]*\)$/\2/p')

            if [[ -n "$TAG" ]]; then
              npm publish --tag $TAG
            elif [[ -z "$TAG" ]]; then
              npm publish
            fi

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  deploy_staging:
    jobs:
      - deploy-not-release:
          context: techgreens-context
          filters:
            tags:
              ignore: /^v.*/